/**
 * Chat context for CLI providers (Codex CLI, Claude Code).
 *
 * These providers cannot run the backend agent loop: the backend only
 * retrieves, and the answer is generated by the CLI from a prompt this
 * side assembles. Two things in that hand-off left the CLI answering
 * blind, and both are decided here so the chat panel never has to know
 * the details:
 *
 * - Skills. With a CLI provider the backend planner is unavailable and
 *   its fallback wiki search is skipped whenever the request carries
 *   skills. In "auto" mode the chat sends every installed skill, so the
 *   search never ran. Auto-mode skills are of no use on this path, so
 *   they are not sent.
 * - Page text. The backend returns title, path and a short snippet per
 *   retrieved page. That is enough to cite a page but not to answer from
 *   it, so the text of the retrieved wiki pages is appended, bounded.
 */

export interface CliContextReference {
  title: string
  path: string
  kind?: string
}

export interface CliRetrievedContextInput {
  /** What the backend returned as retrieval summary (titles and snippets). */
  summary: string
  references: CliContextReference[]
  /** Reads a project-relative page; a rejection only drops that page. */
  readPage: (path: string) => Promise<string>
}

export const CLI_CONTEXT_MAX_PAGES = 10
export const CLI_CONTEXT_PAGE_CHARS = 12_000
export const CLI_CONTEXT_TOTAL_CHARS = 60_000

const TRUNCATION_MARK = "\n[page truncated]"

/**
 * Pages to ask the backend for. The CLI answers only from what it is
 * handed, so every mode but "fast" asks for the most the backend allows.
 */
export function cliSearchTopK(agentMode: string): number {
  return agentMode === "fast" ? 5 : CLI_CONTEXT_MAX_PAGES
}

export function cliRequestSkills(skillMode: "auto" | "explicit", skills: string[]): string[] {
  return skillMode === "auto" ? [] : skills
}

function isWikiPage(reference: CliContextReference): boolean {
  const path = reference.path.replace(/\\/g, "/")
  return path.startsWith("wiki/") && path.toLowerCase().endsWith(".md")
}

function escapeAttribute(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;")
}

export async function buildCliRetrievedContext(input: CliRetrievedContextInput): Promise<string> {
  const seen = new Set<string>()
  const pages = input.references.filter((reference) => {
    if (!isWikiPage(reference) || seen.has(reference.path)) return false
    seen.add(reference.path)
    return true
  }).slice(0, CLI_CONTEXT_MAX_PAGES)

  const contents = await Promise.all(
    pages.map((page) => input.readPage(page.path).catch(() => "")),
  )

  const blocks: string[] = []
  let remaining = CLI_CONTEXT_TOTAL_CHARS
  pages.forEach((page, index) => {
    const text = contents[index].trim()
    if (!text || remaining <= 0) return
    const limit = Math.min(CLI_CONTEXT_PAGE_CHARS, remaining)
    const body = text.length > limit ? `${text.slice(0, limit)}${TRUNCATION_MARK}` : text
    remaining -= Math.min(text.length, limit)
    blocks.push(
      `<page path="${escapeAttribute(page.path)}" title="${escapeAttribute(page.title)}">\n${body}\n</page>`,
    )
  })

  if (blocks.length === 0) return input.summary
  return [
    input.summary,
    "Full text of the retrieved wiki pages. Answer from this text and cite the page it comes from:",
    ...blocks,
  ].filter((part) => part.trim().length > 0).join("\n\n")
}
